name: fanlify_facebook_share
description: Native Facebook link share plugin for Fanlify.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fanlify.facebookshare
        pluginClass: FanlifyFacebookSharePlugin
      ios:
        pluginClass: FanlifyFacebookSharePlugin
